In [2]:
import pandas as pd
from sklearn.metrics import precision_score, accuracy_score, recall_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

In [3]:
heart_df = pd.read_csv("heart.csv")
heart_df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [4]:
X = heart_df.drop("target", axis=1)
y = heart_df["target"]

In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [6]:
scaler = StandardScaler()
X_train_scaler = scaler.fit_transform(X_train)
X_test_scaler = scaler.transform(X_test)

In [7]:
X_train_scaler

array([[-1.35679832,  0.72250438,  0.00809909, ...,  0.95390513,
        -0.68970073, -0.50904773],
       [ 0.38508599,  0.72250438, -0.97189094, ...,  0.95390513,
        -0.68970073,  1.17848036],
       [-0.92132724,  0.72250438,  0.98808912, ..., -0.69498803,
        -0.68970073, -0.50904773],
       ...,
       [ 1.58263146,  0.72250438,  1.96807914, ..., -0.69498803,
         0.32186034, -0.50904773],
       [-0.92132724,  0.72250438, -0.97189094, ...,  0.95390513,
        -0.68970073,  1.17848036],
       [ 0.92942484, -1.38407465,  0.00809909, ...,  0.95390513,
         1.33342142, -0.50904773]], shape=(242, 13))

In [8]:
knn_classifier = KNeighborsClassifier(n_neighbors=3)
knn_classifier.fit(X_train_scaler, y_train)

KNeighborsClassifier(n_neighbors=3)

In [9]:
y_pred = knn_classifier.predict(X_test_scaler)

In [10]:
# Evaluation 

print("Recall score: ", recall_score(y_test, y_pred))
print("Accuracy: ", accuracy_score(y_test, y_pred))
print("Precision: ", precision_score(y_test, y_pred))

Recall score:  0.78125
Accuracy:  0.8524590163934426
Precision:  0.9259259259259259

In [11]:
# For k = 5

knn_classifier = KNeighborsClassifier(n_neighbors=5)
knn_classifier.fit(X_train_scaler, y_train)

y_pred = knn_classifier.predict(X_test_scaler)

# Evaluation 
print("Recall score: ", recall_score(y_test, y_pred))
print("Accuracy: ", accuracy_score(y_test, y_pred))
print("Precision: ", precision_score(y_test, y_pred))

Recall score:  0.875
Accuracy:  0.9016393442622951
Precision:  0.9333333333333333

In [12]:
# For k = 7 --> Best Score 

knn_classifier = KNeighborsClassifier(n_neighbors=7)
knn_classifier.fit(X_train_scaler, y_train)

y_pred = knn_classifier.predict(X_test_scaler)

# Evaluation 
print("Recall score: ", recall_score(y_test, y_pred))
print("Accuracy: ", accuracy_score(y_test, y_pred))
print("Precision: ", precision_score(y_test, y_pred))

Recall score:  0.90625
Accuracy:  0.9180327868852459
Precision:  0.9354838709677419

In [20]:
# For k = 9

knn_classifier = KNeighborsClassifier(n_neighbors=9)
knn_classifier.fit(X_train_scaler, y_train)

y_pred = knn_classifier.predict(X_test_scaler)

# Evaluation 
print("Recall score: ", recall_score(y_test, y_pred))
print("Accuracy: ", accuracy_score(y_test, y_pred))
print("Precision: ", precision_score(y_test, y_pred))

Recall score:  0.875
Accuracy:  0.9016393442622951
Precision:  0.9333333333333333

In [22]:
# Cross validation -> hyperparameter tuning using GridSearchCV

from sklearn.model_selection import GridSearchCV

classifier = KNeighborsClassifier()
param_grid = {"n_neighbors": [3, 5, 7, 9]}

classifierCV = GridSearchCV(
    classifier,
    param_grid,
    cv=5,
    scoring="recall"
)

classifierCV.fit(X_train_scaler, y_train)

y_pred = classifierCV.predict(X_test_scaler)

# Evaluation 
print("Recall score: ", recall_score(y_test, y_pred))
print("Accuracy: ", accuracy_score(y_test, y_pred))
print("Precision: ", precision_score(y_test, y_pred))


# Results 
res = pd.DataFrame(classifierCV.cv_results_)
res

Recall score:  0.90625
Accuracy:  0.9180327868852459
Precision:  0.9354838709677419

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_n_neighbors,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002930,0.000632,0.009587,0.000650,3,{'n_neighbors': 3},0.851852,0.814815,0.962963,0.884615,0.807692,0.864387,0.056489,2
1,0.001472,0.000823,0.004828,0.000912,5,{'n_neighbors': 5},0.777778,0.814815,0.925926,0.923077,0.846154,0.857550,0.058803,3
2,0.001095,0.000164,0.004428,0.000851,7,{'n_neighbors': 7},0.814815,0.925926,0.925926,0.846154,0.846154,0.871795,0.045655,1
3,0.001130,0.000172,0.003815,0.000418,9,{'n_neighbors': 9},0.777778,0.888889,0.925926,0.846154,0.846154,0.856980,0.049556,4

In [24]:
print(res[["param_n_neighbors", "mean_test_score"]])
print(classifierCV.best_params_)

   param_n_neighbors  mean_test_score
0                  3         0.864387
1                  5         0.857550
2                  7         0.871795
3                  9         0.856980
{'n_neighbors': 7}

In [ ]:
# 1. Calculate μ and σ ONLY from Fold 2+3+4+5
#              ↓
# 2. Scale Fold 2+3+4+5 using those μ and σ
#              ↓
# 3. Scale Fold 1 using the SAME μ and σ
#              ↓
# 4. Train model on Fold 2+3+4+5
#              ↓
# 5. Predict Fold 1

In [ ]:
# What goes wrong without Pipeline?

# Imagine you do this first:

# Code:
# scaler.fit_transform(X_train)

# Remember, X_train contains all 800 samples, including the samples that Cross-Validation will later use as validation folds.

# So your scaler calculates:

# μ=mean of all 800 samples
# σ=standard deviation of all 800 samples

# Then you give this already-scaled data to GridSearchCV.

# Now when GridSearchCV says:

# "Okay, Fold 1 is my validation data."

# Fold 1 has already influenced the mean and standard deviation.

# That's the leakage.

In [26]:
# Pipeline -->  makes the scaling happen inside each CV iteration.
from sklearn.pipeline import Pipeline

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# steps
pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('knn', KNeighborsClassifier())
])

param_grid = {"knn__n_neighbors": [3, 5, 7, 9]} # knn__n_neighbors --> knn inside n_neighbors is there

classifierCV = GridSearchCV(
    pipeline,
    param_grid,
    cv=5,
    scoring="recall"
)

classifierCV.fit(X_train, y_train)

y_pred = classifierCV.predict(X_test)


# Evaluation 
print("Recall score: ", recall_score(y_test, y_pred))
print("Accuracy: ", accuracy_score(y_test, y_pred))
print("Precision: ", precision_score(y_test, y_pred))


# Results 
print(classifierCV.best_params_)

Recall score:  0.90625
Accuracy:  0.9180327868852459
Precision:  0.9354838709677419
{'knn__n_neighbors': 7}